# Generated by Django 3.1.1 on 2020-09-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_event_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='parent_notes',
        ),
        migrations.AddField(
            model_name='note',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.lecture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usermodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
