# Generated by Django 3.1.1 on 2020-09-21 15:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200920_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='lectures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
