# Generated by Django 3.1.1 on 2020-09-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200920_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='thumbnail',
            field=models.URLField(default='http://hydro.ijs.si/v015/c2/yi4axnf3yag33hxci43kggzg5luznvcb.jpg'),
            preserve_default=False,
        ),
    ]
