# Generated by Django 3.1.1 on 2020-09-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lecture_thumbnail'),
        ('api', '0005_auto_20200921_1733'),
    ]

    operations = [
    ]
