# Generated by Django 3.1.1 on 2020-09-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20200921_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='author',
            new_name='user',
        ),
    ]
