# Generated by Django 3.1.1 on 2020-09-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200921_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['lecture', 'user', 'timestamp']},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['lecture', 'timestamp']},
        ),
    ]
