# Generated by Django 3.1.1 on 2020-10-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201003_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_model',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.usermodel'),
        ),
    ]
