# Generated by Django 3.1.1 on 2020-10-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201003_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usermodel'),
        ),
    ]
