# Generated by Django 3.1.2 on 2020-10-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201003_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='stargazers',
            field=models.ManyToManyField(to='api.UserModel'),
        ),
    ]
