# Generated by Django 3.1.2 on 2020-10-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_lecture_stargazers'),
        ('api', '0015_auto_20201004_0945'),
    ]

    operations = [
    ]
