# Generated by Django 3.1.2 on 2020-10-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20201008_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.Category'),
        ),
    ]
