# Generated by Django 3.1.2 on 2020-10-10 21:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201008_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lectures_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.RemoveField(
            model_name='event',
            name='lectures',
        ),
        migrations.AddField(
            model_name='event',
            name='lectures',
            field=models.ManyToManyField(blank=True, to='api.Lecture'),
        ),
    ]
