# Generated by Django 3.1.2 on 2020-10-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201010_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='stargazers',
            field=models.ManyToManyField(blank=True, to='api.UserModel'),
        ),
    ]
