# Generated by Django 3.1.2 on 2020-10-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201010_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lectures',
        ),
        migrations.AddField(
            model_name='lecture',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture', to='api.event'),
        ),
    ]
