# Generated by Django 3.1.2 on 2020-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
