# Generated by Django 3.1.2 on 2020-10-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20201030_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='api.Category'),
        ),
    ]
