# Generated by Django 3.1.2 on 2020-11-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_lectureview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureview',
            name='left_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
