# Generated by Django 3.1.2 on 2020-11-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_lectureview_start_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectureview',
            old_name='left_timestamp',
            new_name='end_timestamp',
        ),
    ]
