# Generated by Django 3.1.5 on 2021-07-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_signedforms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signedform',
            old_name='roomNumber',
            new_name='room_number',
        ),
    ]
