# Generated by Django 3.1.5 on 2021-10-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20210727_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedform',
            name='event',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
