# Generated by Django 3.1.1 on 2020-09-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lectures.lecture'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
