# Generated by Django 3.1.1 on 2020-09-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200909_1901'),
        ('lectures', '0002_auto_20200909_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lectures.lecture'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel'),
        ),
    ]
