# Generated by Django 3.1.1 on 2020-09-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200909_1901'),
        ('lectures', '0003_auto_20200909_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel'),
        ),
    ]
