# Generated by Django 3.1.1 on 2020-09-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20200909_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lectures.lecture'),
        ),
    ]
