# Generated by Django 3.1.1 on 2020-09-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200909_1901'),
        ('lectures', '0005_auto_20200909_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_author', to='users.usermodel'),
        ),
    ]
